name: Deploy Azure Container App with GHCR

env:
  AZURE_CONTAINER_APP_NAME: demo-app
  AZURE_GROUP_NAME: openai-rg

on:
  workflow_dispatch: # Manually triggered in GitHub UI

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Lowercase Repo Name for Tagging
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and Push Image to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    name: Deploy to Azure Container App
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Lowercase Repo Name (Again)
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Deploy Container to Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt

            # Authenticate Azure to pull from GHCR
            az containerapp registry set \
              --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
              --resource-group ${{ env.AZURE_GROUP_NAME }} \
              --server ghcr.io \
              --username ${{ github.actor }} \
              --password ${{ secrets.GHCR_PAT }}


            # Set environment variables for the app (update as needed)
            az containerapp update \
              --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
              --resource-group ${{ env.AZURE_GROUP_NAME }} \
              --set-env-vars \
                OPENAI_API_TYPE=azure \
                OPENAI_API_BASE=https://demo-alfredo-openai.openai.azure.com/ \
                OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
                OPENAI_API_VERSION="2023-07-01-preview" \
                SEARCH_SERVICE_NAME="https://demo-alfredo.search.windows.net" \
                SEARCH_API_KEY=${{ secrets.SEARCH_SERVICE_API_KEY }} \
                SEARCH_INDEX_NAME="demo-alfredo"

            # Update CPU/memory (optional)
            az containerapp update \
              --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
              --resource-group ${{ env.AZURE_GROUP_NAME }} \
              --cpu 2 \
              --memory 4Gi

            # Deploy latest image
            az containerapp update \
              --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
              --resource-group ${{ env.AZURE_GROUP_NAME }} \
              --image ghcr.io/${{ env.REPO }}:${{ github.sha }}
